---
title: "Salmon Escapement"
author: "Antonia Androski"
date: "10/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries, warning = FALSE, message = FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(cowplot)
```


```{r Read in Data}
esc <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e", 
  method = "libcurl"), 
  stringsAsFactors = FALSE)

#The function tryCatch can be useful if you need to switch between working from the internet and working from local files - it downloads the file when you need it.
```

# Calculate annual escapement for salmon species

```{r, results = "hide"}
# Change sample dates to years but keep sample dates, change year to numeric, group columns and summarize by calculating total escapement and 5 most common species
annual_esc <- esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-", remove = FALSE) %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Year, SASAP.Region, Species) %>% 
  summarize(total_escapement = sum(DailyCount)) %>%
  filter(Species %in% c("Chinook", "Sockeye", "Chum", "Pink", "Coho"))
#The %in% operator does the same thing as: filter(Species == "Chinook" | Species == "Sockeye" | etc...)
#You can also create a species list vector before running this filter, e.g. species_list <- c("Chinook", "Sockeye", etc...). This might be good since you can may want the list for other purposes. 

head(annual_esc)
```

# Visualize escapement with ggplot

Total Escapement by Region and Species

```{r Plot, echo = FALSE}
ggplot(data = annual_esc, mapping = aes(x = Species, y = total_escapement, fill = SASAP.Region)) +
  geom_col()
#You would think that the first part of this would make a plot, but it just sets up the plot without any points. You have to specify the geometry to get points.
```

Kodiak Escapement Over Time by Species

```{r, echo = FALSE}
my_theme <- theme_bw() + theme(legend.position = "top")

ggplot(data = filter(annual_esc, SASAP.Region == "Kodiak"), 
       mapping = aes(x = Year, y = total_escapement, color = Species)) +
geom_point() + geom_line() + scale_color_brewer(palette = "Dark2") + ylab("Escapement (no. fish)") + ggtitle("Kodiak Salmon Escapement") + my_theme
```

Excapement over time: all regions

```{r, fig.width = 7, fig.height = 20, echo = FALSE}
fig1 <- ggplot(annual_esc, aes(x = Year, y = total_escapement, color = Species)) + geom_point() + geom_line() + facet_wrap(~SASAP.Region, scales = "free_y", ncol = 1) + my_theme

fig1
#saving the plot:
ggsave("escapement.png", fig1, width = 12, height = 7, units = "in")
```

# Map sampling locations